### PR TITLE
gorge to scan local modules directory

### PR DESCRIPTION
**Pull request by johnwarburton**
Hi @dadav 

Use case is `gorge` running as a local puppet forge for in house build puppet modules

When a new module is built, we would drop it into the local modules directory

We would like `gorge` to scan the local modules directory on a regular basis to pick up module updates. This PR gives us the ability to scan the local module on a regular basis. The default is the current behaviour - only scan on startup

Please let me know if you need anything else to accept this PR

Regards

John

### CODE REVIEW

**Comment by dadav** [comment]
Hi @johnwarburton ,

Thanks for this awesome PR. I think we need a way to make sure to cleanup that goroutine...

**Comment by johnwarburton** [comment]
Thanks @dadav - any suggestions on cleaning up the goroutine? This is my first attempt at writing go, so any pointers would be appreciated

**Comment by johnwarburton** [comment]
Hi @dadav - I had a chat with one of our `go` gurus and they suggested tidying up the code to remove some redundancies - was this what you meant by "cleanup"?

Thanks!

**Comment by dadav** [comment]
> Hi @dadav - I had a chat with one of our `go` gurus and they suggested tidying up the code to remove some redundancies - was this what you meant by "cleanup"?
> 
> Thanks!

With cleanup I mean to prevent goroutine leaks. We need a way to tell the goroutine when to exit, which usually is when the user presses Ctrl+c or SIGTERM is sent.

**Comment by johnwarburton** [comment]
wow - thanks @dadav - next level stuff!

**Pull request merged**
